Setup last layer
os-climate/neural-magic-notebook pull request #2
Opened 2022-02-15 08:52 UTC by pacospace

2022-02-16 14:18 UTC, pacospace commented
@harshad16 PTAL :)

2022-02-16 17:42 UTC, harshad16 requested changes
lgtm 
just one minor fix needed

2022-02-16 17:42 UTC, harshad16 commented on .s2i/environment
> +THAMOS_RUNTIME_ENVIRONMENT=""
```suggestion
THAMOS_RUNTIME_ENVIRONMENT=
```
Tested it , the `""` were causing an issue.
can you please remove it.

2022-02-17 13:54 UTC, harshad16 commented
@pacospace the ci check this pr has requires contributor to have signed commits.
As we committed the suggestions they are breaking.
 you might have to squash the commits into one.

2022-02-17 13:58 UTC, pacospace commented
> @pacospace the ci check this pr has requires contributor to have signed commits. As we committed the suggestions they are breaking. you might have to squash the commits into one.

Thanks @harshad16, I squashed them.

2022-02-17 16:10 UTC, merged